version: "2.1"

volumes:
  html:
  mysql:

services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - html:/var/www/html
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.local *.balena-devices.com"
    depends_on:
      - mariadb
      - redis

  # https://hub.docker.com/_/nginx/
  nginx:
    build: nginx
    ports:
      - 80:80/tcp
    volumes:
      - html:/var/www/html:ro
    depends_on:
      - nextcloud

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  mariadb:
    image: yobasystems/alpine-mariadb:10.6.9
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command:
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=512
      - --innodb-rollback-on-timeout=OFF
      - --innodb-lock-wait-timeout=50
      - --binlog-format=ROW
      # - --skip-innodb-read-only-compressed

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.2.7-alpine
    command: redis-server --requirepass nextcloud

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: nextcloud
