version: "2.1"

volumes:
  html:
  mysql:

services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - html:/var/www/html
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.local *.balena-devices.com"
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_LIMIT: 2G
    depends_on:
      - mariadb
      - redis

  # https://hub.docker.com/_/nginx/
  nginx:
    build: nginx
    ports:
      - 80:80/tcp
    volumes:
      - html:/var/www/html:ro
    depends_on:
      - nextcloud

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  mariadb:
    image: yobasystems/alpine-mariadb:10.11.6@sha256:b75cd035f9502d5e77f2ff17acee78368341aa1ef01eb5f85a2c9006fc891123
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command:
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --binlog-format=ROW
      - --innodb-file-per-table=1

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.2.14-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    command: redis-server --requirepass nextcloud

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname@sha256:b923d6ea886ec48125d2c49e431638d2ef6f4adac574b729b4135cfade3ffdce
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: nextcloud
