name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        fleet:
          [
            gh_klutchell/nextcloud-aarch64,
            gh_klutchell/nextcloud-amd64,
            gh_klutchell/nextcloud-armv7hf,
          ]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: balena-io/deploy-to-balena-action@075f85cd8a201967bdaa5983d17a59ef348bcb3d # v1.1.10
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
