name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        fleet:
          [
            gh_klutchell/nextcloud-aarch64,
            gh_klutchell/nextcloud-amd64,
            gh_klutchell/nextcloud-armv7hf,
          ]

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: balena-io/deploy-to-balena-action@32ba4d483c97666a46cb27bba86633e7a951cd51 # v2.0.77
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
